simulation_input_dir: data/1fme
num_workers: 4
simulations_per_train: 6
simulations_per_inference: 1
num_total_simulations: 1000

compute_settings:
  name: workstation
  available_accelerators: ["0", "1", "2", "3"]

simulation_settings:
  simulation_length_ns: 10
  report_interval_ps: 10
  temperature_kelvin: 300
  rmsd_reference_pdb: data/1fme/1FME-folded.pdb

train_settings:
  cvae_settings_yaml: examples/bba-folding-workstation/cvae-prod-settings.yaml

inference_settings:
  cvae_settings_yaml: examples/bba-folding-workstation/cvae-prod-settings.yaml
  num_outliers: 100
